# fly.toml app configuration file generated for todo-app-by-jean on 2024-10-18T23:31:14+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-app-by-jean'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
